name: pr-validation
on: 
  pull_request:
   types:
    - opened
    - synchronize
  push:
      branches:
        - develop

jobs:
  pr-validation-jab:
   runs-on: ubuntu-latest
   steps:
     - name: wellcome steps       
       run: echo " Wellcome to github actions"
     - name:  steps 2
       run: echo "Second steps"

